theme: jekyll-theme-chirpy

lang: en
timezone: America/Chicago

title: PG
tagline: ""
description: >-
  Personal blog of Pradeep Gangadharaiah.

url: "https://pradeepg.me"

github:
  username: itsprdp

social:
  name: Pradeep Gangadharaiah
  email: ""
  links:
    - https://www.linkedin.com/in/pgangadharaiah

avatar: assets/img/avatar.jpg

search: false

toc: true

paginate: 10

permalink: /:year/:month/:day/:title/

# Collections for tab pages
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: development
