lang: en
timezone: America/Chicago

title: PG
description: >-
  Personal blog of Pradeep Gangadharaiah.

url: "https://pradeepg.me"

github:
  username: itsprdp

social:
  name: Pradeep Gangadharaiah
  email: ""
  links:
    - https://www.linkedin.com/in/pgangadharaiah

avatar: assets/img/avatar.jpg

paginate: 10
paginate_path: "/page:num/"

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
